from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
branch_whitelist = ["main"]
skip_untracked = false

pre_bump_hooks = [
    "cargo set-version {{version}}",
    "cargo update --workspace --offline",
    "cog changelog",
]
post_bump_hooks = []

[git_hooks]
[git_hooks.pre-commit]
script = "./pre-commit.sh"

[changelog]
path = "CHANGELOG.md"
authors = [{ username = "containerscrew", signature = "dcrookie" }]

[bump_profiles]
